on:
  push:
    branches:
      - main

name: Release
jobs:
  ghcr:
    name: GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: aaditgupta21
          password: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/aaditgupta21/counter .
      - run: docker push ghcr.io/aaditgupta21/counter
      - run: docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl https://server.aaditgupta.tech --caproverPassword ${{ secrets.CAPROVER_PASSWORD }} --caproverApp counter --imageName ghcr.io/aaditgupta21/counter
